### PR TITLE
Import improvements

### PR DESCRIPTION
**Pull request by fingolfin**
I just discovered the fork of this repository by @reiniscirpons. Really cool! Opening this PR so I won't forget where to look for it in the future.

If you are interested in "completing" this, I'd be happy to migrate the repository to the `gap-system` GitHub organization and give you direct write access there, to make it more official and perhaps invite others to contribute. Thoughts?

### CODE REVIEW

**Comment by reiniscirpons** [comment]
Hi @fingolfin, thank you for the kind words! I actually meant to get in contact with you about exactly this, but marking etc. got in the way and I forgot.

I would like to finishing the grammar. The main hurdle left at the moment is handling leading period floats e.g. `.1` and correctly distinguishing them from record selectors (it seems this is not really used much in the `GAP` corpus, but is the last big language feature missing). The suggestion to migrate it to the `gap-system` organization is good and I would very much appreciate write access. I am also no expert in writing `tree-sitter` grammars, so contributions and suggestions from others would be greatly appreciated. Overall I agree with your proposal.

Having the grammar in as part of the official `gap-system` repository also opens up new possibilities of integrating `tree-sitter` with `GAP` itself, e.g. improving syntax highlighting in the interactive `GAP` sessions. I would also like to mention the [`tree-sitter-gaptst`](https://github.com/reiniscirpons/tree-sitter-gaptst) grammar I've been working on for parsing `.tst` files, which uses `tree-sitter-gap` for language injections. Do you think it would make sense to migrate `tree-sitter-gaptst` to the `gap-system` organization as well, or should this project be separate at the moment?

**Comment by fingolfin** [comment]
Great to hear you are interested in finishing this :-)

Regarding float literals like `.1` -- IMHO it would also be OK to ignore them for now -- as you say, they are rare to use (and I think it was a mistake to introduce them in the first place; I've been thinking about pushing towards deprecating and ultimately removing this, see https://github.com/gap-system/gap/pull/3280). That said, for now it is there, and I wouldn't want to stop you from implementing it -- but if that's really the only thing stopping this from being "ready", we shouldn't hesitate to make a first "release" now (I guess that would include registering it with npm, so that `npm install tree-sitter-gap tree-sitter` would work, and submitting it for inclusion in the list on https://tree-sitter.github.io/tree-sitter/)

Having `tree-sitter-gaptst` on gap-system sounds sensible as well.

My plan would to migrate this repository here to `gap-system`, then give you write access, so that you can merge / push / integrate your work as you deem fit. I'll wait a bit with that in case you have a better suggestion.

**Comment by reiniscirpons** [comment]
I believe using the external scanner I should be able to implement leading period floats, its just that until now there were lower hanging fruit which I've prioritized. The suggestion about making a first release and submitting it to registries is good, I will look into that once the migration is done.

I agree with the proposed plan, no better suggestions here.

**Comment by fingolfin** [comment]
@reiniscirpons I've transferred this repository and gave you "maintainer" access (if that turns out to be too limited I can still upgrade it to admin, just let me know if you run into blocks).

I've also sent you an invite to the `gap-system` GitHub org. Once you accepted that, you should be able to transfer your other treesitter repository. 

Let me know if you need assistance with any of that.

Finally, you may wish to consider joining the GAP Slack (a multi user chat system) to be able to chat with others about this or other GAP related stuff:  https://gap-system.org/slack should allow you to join.

**Pull request merged**
